export const GET_INFO_PLAYER = 'GET_INFO_PLAYER';
export const GET_PICTURE = 'GET_PICTURE';
export const UPDATE_SCORE = 'UPDATE_SCORE';
export const UPDATE_ASSERTIONS = 'UPDATE_ASSERTION';
export const NEW_SCORE = 'NEW_SCORE';
